import { expect, test } from '@playwright/test'
import { createConfirmedUser, itemStep, seedItem, seedVitrine, signIn, uniqueSubdomain } from './helpers'

test('grupos a partir de modelos, ligados ao item, e formulário da sacola', async ({ page }) => {
  const user = await createConfirmedUser('complementos')
  const vitrine = await seedVitrine(user.id, { type: 'comida' })
  const item = await seedItem(vitrine, user.id, { name: 'X-Bacon', priceCents: 2590 })
  await signIn(page, user.email, user.password)

  await page.goto(`/painel/vitrines/${vitrine.id}/complementos`)
  const novo = page.getByRole('form', { name: 'Novo grupo' })
  await novo.getByRole('button', { name: 'Salvar grupo' }).click()
  await expect(novo.getByText('Informe o nome do grupo.')).toBeVisible()

  await page.getByLabel('Começar de um modelo').selectOption({ label: 'Ponto da carne' })
  await expect(page.getByRole('form', { name: 'Novo grupo' }).getByLabel('Nome do grupo')).toHaveValue('Ponto da carne')
  await page.getByRole('form', { name: 'Novo grupo' }).getByRole('button', { name: 'Salvar grupo' }).click()
  await expect(page.getByText('Grupo salvo.')).toBeVisible()
  await expect(page.getByRole('form', { name: 'Grupo Ponto da carne' })).toBeVisible()

  await page.getByLabel('Começar de um modelo').selectOption({ label: 'Sabores de pizza' })
  const sabores = page.getByRole('form', { name: 'Novo grupo' })
  await expect(sabores.getByRole('radio', { name: 'Sabores de pizza' })).toBeChecked()
  await sabores.getByLabel('Preço dos sabores').selectOption({ label: 'Média' })
  await sabores.getByRole('button', { name: 'Salvar grupo' }).click()
  await expect(page.getByRole('form', { name: 'Grupo Sabores' })).toBeVisible()
  await expect(page.getByRole('form', { name: 'Grupo Sabores' }).getByLabel('Preço dos sabores')).toHaveValue('average')

  await page.goto(`/painel/vitrines/${vitrine.id}/itens/${item.id}`)
  await itemStep(page, 'Extras')
  await page.getByLabel('Ponto da carne').check()
  await page.getByLabel('Sabores').check()
  await page.getByRole('button', { name: 'Salvar item' }).click()
  await expect(page.getByText('Item salvo.')).toBeVisible()
  await page.goto(`/painel/vitrines/${vitrine.id}/itens/${item.id}`)
  await itemStep(page, 'Extras')
  await expect(page.getByLabel('Ponto da carne')).toBeChecked()
  await expect(page.getByLabel('Sabores')).toBeChecked()

  await page.goto(`/painel/vitrines/${vitrine.id}/mensagens`)
  await expect(page.getByLabel('Usar sacola')).toBeChecked()
  await expect(page.getByLabel('Retirada ou entrega')).toHaveValue('required')
  await page.getByLabel('Formas de pagamento (uma por linha)').fill('')
  await page.getByRole('button', { name: 'Salvar mensagens' }).click()
  await expect(page.getByText('Informe pelo menos uma forma de pagamento.')).toBeVisible()
  await page.getByLabel('Formas de pagamento (uma por linha)').fill('Pix\nDinheiro')
  await page.getByRole('button', { name: 'Salvar mensagens' }).click()
  await expect(page.getByText('Mensagens salvas.')).toBeVisible()
})

test('assistente cria vitrine de Comida com sacola ligada', async ({ page }) => {
  const user = await createConfirmedUser('comida')
  await signIn(page, user.email, user.password)

  await page.goto('/painel/vitrines/nova')
  await page.getByLabel('Comida').check()
  await page.getByRole('button', { name: 'Continuar' }).click()
  await page.getByLabel('Nome da vitrine').fill('Burger Teste')
  await page.getByLabel('Endereço da vitrine', { exact: true }).fill(uniqueSubdomain('burger'))
  await page.getByRole('button', { name: 'Continuar' }).click()
  await page.getByLabel('WhatsApp', { exact: true }).fill('(11) 98765-4321')
  await page.getByRole('button', { name: 'Continuar' }).click()
  await page.getByRole('button', { name: 'Criar vitrine' }).click()
  await expect(page.getByRole('heading', { name: 'Lanches' })).toBeVisible()

  await page.getByRole('link', { name: 'Sacola e mensagens' }).click()
  await expect(page.getByLabel('Usar sacola')).toBeChecked()
  await expect(page.getByLabel('Texto padrão do botão')).toHaveValue('Pedir')
  await expect(page.getByLabel('Forma de pagamento', { exact: true })).toHaveValue('required')
})
